version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
      - image: circleci/mysql:5.7

    working_directory: /go/src/github.com/humamfauzi/Registration
    steps:
      - checkout

      - run: go get -v -t -d ./...
      - run: go test -v ./...
