version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: humam123
          MYSQL_DATABASE: registration
        ports:
          - 3306:3306

    working_directory: /go/src/github.com/humamfauzi/Registration
    steps:
      - checkout

      - run:
          name: Get Package
          command:  go get -v -t -d ./...
      - run:
          name: Test Go Files
          command: go test -v ./...
